---
version: 3

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-24/ee-supported-rhel8:latest

dependencies:
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt

additional_build_files:
    - src: ansible.cfg
      dest: configs

additional_build_steps:
  prepend_base: |
    RUN whoami
    RUN cat /etc/os-release
    RUN /usr/bin/python3 -m pip install --upgrade pip setuptools
  append_base:
    - RUN echo This is a post-install command!

options:
  package_manager_path: /usr/bin/microdnf

