---
collections:
  - name: ibm.ibm_zos_core
#  - name: ibm.ibm_zhmc
  - name: ibm.ibm_zos_ims
  - name: ibm.ibm_zos_cics
  - name: ibm.ibm_zosmf
  - name: servicenow.itsm
  - name: amazon.aws
#  - name: amazon.cloud
#    type: git
#    source: https://github.com/ansible-collections/amazon.cloud.git
  - name: vmware.vmware_rest
  - name: vmware.vmware
  - name: ansible.controller
  - name: awx.awx
  - name: kubernetes.core
  - name: ansible.posix
  - name: ansible.utils
  - name: ansible.windows
  - name: community.aws
  - name: community.vmware
  - name: community.crypto
  - name: community.general
  - name: containers.podman
  - name: cloud.terraform
